name: 'supply_chain_analytics'
version: '1.0.0'
config-version: 2

profile: 'supply_chain'

model-paths: ["models"]
test-paths: ["tests"]
data-paths: ["data"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
docs-paths: ["docs"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  execution_date: '{{ run_started_at }}'
  model_version: 'v1.0'

models:
  supply_chain_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
